### ISSUE TITLE
Issues running in Crostinux Linux.

### ISSUE THREAD

**Issue by cirby1** [Dynamique-Zak/Zelda_BlenderGame#2]
Hello, 

I'm having issues trying to figure out how to run the program in Crostini Linux (Terminal in ChromeOS). If possible, can you provide step-by-step instructions? 

So far I have installed Blender using this video: https://www.youtube.com/watch?v=b6HJjXXH4dk

Afterwards, I'm stuck on what file to run with your git repo. Do I just run the python file in the terminal or in Blender? I'm having issues with the dx_bge folder. 

-Thanks!

**Comment by SomndusStudio** [comment]
Hello my Dear,

I don't think this will work because it's developped from an very elder version of Blender (2.76) 7 years ago.

Since some blender version (and 3.3 from you showed me), Blender Game Engine are removed, it's why dx_bge don't work (bge for Blender Game Engine)

**Comment by cirby1** [comment]
Thanks for the response. Well that makes sense. To update, well I was able to download the Blender 2.7x version. What's the command to run the game? Do I run it within Blender or just on the command line? "python3 manager.py" throws this error?:

**python3 manager.py
Traceback (most recent call last):
  File "/home/calvinirby01/PythonStudies/games/Zelda_BlenderGame/manager.py", line 32, in <module>
    execute(sys.argv[1:])
  File "/home/calvinirby01/PythonStudies/games/Zelda_BlenderGame/manager.py", line 14, in execute
    command_name = args[0]
IndexError: list index out of range**

Any reasons as to why it is showing like this?

**Comment by cirby1** [comment]
Hello again, I really admire your project here and since I am teaching Python to high schoolers, is there any way that this game could get preserved or exported? Or maybe you can do an updated HOW-TO series on how to make it? Please let me know!

**Comment by mhbxyz** [comment]
Hello @cirby1,
If you want to to export the game in executable form, you need to download Blender 2.76, open the project with it and use the export feature of Blender. Here is the link to the official repository for binaries: [https://download.blender.org/release/Blender2.76/](https://download.blender.org/release/Blender2.76/)

**Comment by cirby1** [comment]
@mhbxyz @SomndusStudio It was successfully ran. I was also able to export it. Thanks!
